name: crewai

services:
  # PostgreSQL database with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
      POSTGRES_USER: ${POSTGRES_USER:-crewai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-crewai} -d ${POSTGRES_DB:-crewai}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
  # Redis for caching and queue backend
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # FastAPI Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: crewai-backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-crewai}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-crewai}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      - AUTO_MIGRATE_ON_STARTUP=${AUTO_MIGRATE_ON_STARTUP:-true}
      - FAIL_ON_MIGRATION_ERROR=${FAIL_ON_MIGRATION_ERROR:-true}
      - DEBUG=${DEBUG:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    networks:
      - crewai-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ../backend:/app
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Celery Worker for async task processing
  celery-worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: crewai-celery-worker
    command: celery -A celery_app worker --loglevel=info --queues=crew_execution,cleanup
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-crewai}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-crewai}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
    networks:
      - crewai-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ../backend:/app
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Celery Flower for monitoring
  celery-flower:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: crewai-celery-flower
    command: celery -A celery_app flower --port=5555
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    networks:
      - crewai-network
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ../backend:/app
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # MLFlow for experiment tracking
  mlflow:
    image: python:3.11-slim
    container_name: crewai-mlflow
    command: >
      bash -c "pip install mlflow[extras]==2.18.0 &&
               mlflow server --host 0.0.0.0 --port 5000
               --backend-store-uri postgresql://${POSTGRES_USER:-crewai}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-crewai}
               --default-artifact-root /mlruns"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-crewai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-crewai}
    ports:
      - "${MLFLOW_PORT:-5001}:5000"
    networks:
      - crewai-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - mlflow_data:/mlruns
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 5000:3000
    volumes:
      - dbgate-data:/root/.dbgate
    networks:
      - crewai-network
    environment:
      CONNECTIONS: con1

      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: ${POSTGRES_USER:-crewai}
      PASSWORD_con1: ${POSTGRES_PASSWORD}
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  dbgate-data:
    driver: local
  mlflow_data:
    driver: local

networks:
  crewai-network:
    driver: bridge
    name: crewai-network
    ipam:
      config:
        - subnet: 172.20.0.0/16 