"""Add LLM node type and table

Revision ID: 9cd2b9bd1513
Revises: 5825db52a6be
Create Date: 2025-06-03 02:37:28.778077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd2b9bd1513'
down_revision: Union[str, None] = '5825db52a6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE', 'AWS_BEDROCK', 'OLLAMA', 'GROQ', 'HUGGINGFACE', 'MISTRAL', 'NVIDIA_NIM', 'FIREWORKS', 'PERPLEXITY', 'SAMBANOVA', 'CEREBRAS', 'OPENROUTER', name='llmproviderenum'), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_p', sa.Integer(), nullable=True),
    sa.Column('frequency_penalty', sa.Integer(), nullable=True),
    sa.Column('presence_penalty', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('streaming', sa.Boolean(), nullable=True),
    sa.Column('response_format', sa.JSON(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_rpm', sa.Integer(), nullable=True),
    sa.Column('stop_sequences', sa.JSON(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('vertex_credentials', sa.Text(), nullable=True),
    sa.Column('aws_region', sa.String(length=50), nullable=True),
    sa.Column('azure_deployment', sa.String(length=255), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('supports_function_calling', sa.Boolean(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=True),
    sa.Column('supports_json_mode', sa.Boolean(), nullable=True),
    sa.Column('cost_per_input_token', sa.Integer(), nullable=True),
    sa.Column('cost_per_output_token', sa.Integer(), nullable=True),
    sa.Column('estimated_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['node_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_nodes_id'), 'llm_nodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_nodes_id'), table_name='llm_nodes')
    op.drop_table('llm_nodes')
    # ### end Alembic commands ###
